export default {
  CMD_FW_INIT: 0x10,
  CMD_FW_SET_ADDRESS: 0x11,
  CMD_FW_ERASE: 0x16,
  CMD_FW_WRITE: 0x17,
  CMD_FW_UPGRADE: 0x18,
  CMD_FW_SECTOR_ERASE: 0x19,
  CMD_FW_FAST_WRITE_SET: 0x20,
  CMD_FW_CONN_PARAM_SET: 0x21,
  CMD_FW_MCU_RESET: 0x22,
  CMD_FW_GET_MTU_SIZE: 0x24,
  CMD_FW_INIT_NEW: 0x27,
  CMD_FW_CREATE: 0x25,
  CMD_FW_OTA_JUMP: 0x28,
  CMD_FW_EXTFLASH_ERASE: 0x29,
  CMD_FW_UPGRADE_FROM_EXTFLASH: 0x2A,
  CMD_FW_SET_BIN_INFO: 0x2B,

  RET_FW_CHECKSUM_ERROR: -1,
  MAX_TRANS_COUNT: 18,
  MAX_TRANS_COUNT2: 20,
  MAX_MORE_DATA_PACKET: 4,


  UI_CMD_UPDATE_OTA_STEP: 0,
  UI_CMD_UPDATE_ERROR_MSG: 1,
  UI_CMD_SCAN_BTN_CHEC10K: 2,
  UI_CMD_SCAN_BTN_UNCHECK: 3,
  UI_CMD_UPDATE_TIMER_COUNTE: 4,


  PXI_BLE_CONFIG: "PXI_BLE_CONFIG",
  PXI_OTA_DEVICE_NAME: "PXI_OTA_DEVICE_NAME",
  PXI_OTA_SERVICE_UUID: "PXI_OTA_SERVICE_UUID",
  PXI_OTA_CHARACTERISTIC_UUID: "PXI_OTA_CHARACTERISTIC_UUID",
  PXI_OTA_PAYLOAD_SIZE: "PXI_OTA_PAYLOAD_SIZE",
  PXI_OTA_WRITE_DELAY: "PXI_OTA_WRITE_DELAY",
  PXI_OTA_WRITE_CHECK_DELAY: "PXI_OTA_WRITE_CHECK_DELAY",
  PXI_OTA_IS_ENABLE_FITLER: "PXI_OTA_IS_ENABLE_FITLER",



  UI_BLE_STATUS_TEXT_DISCOVER: "Android BLE OTA Discovering...",
  UI_BLE_STATUS_TEXT_CONNECTED: "Android BLE OTA Connected",
  UI_BLE_STATUS_TEXT_DISCONNECTED: "Android BLE OTA Disconnected",
  // UI_BLE_STATUS_TEXT_FIND_SERVICE: "Find Characteristics API " + Build.VERSION.SDK_INT,

  UI_BLE_STATUS_TEXT_OTA_INIT: "PXI BLE OTA Init",

  UI_BLE_STATUS_TEXT_OTA_SECTOR_ERASE: "PXI BLE OTA Sector Erase",
  UI_BLE_STATUS_TEXT_OTA_FLASH_ERASE: "PXI BLE OTA Flash Erase",

  UI_BLE_STATUS_TEXT_OTA_SET_FLASH_ADDR: "PXI BLE OTA Set FW info",
  UI_BLE_STATUS_TEXT_OTA_CONNECION_UPDATE: "PXI Connecion Update ",

  UI_BLE_STATUS_TEXT_OTA_CREATE: "PXI BLE OTA Create",
  UI_BLE_STATUS_TEXT_OTA_GET_MTU: "PXI BLE OTA Get MTU",



  PXI_OTA_FAILURE_TEXT_OTA_INIT: "PXI OTA Init Fail ",
  PXI_OTA_FAILURE_TEXT_OTA_INIT_NEW: "PXI OTA Init New Fail ",
  PXI_OTA_FAILURE_TEXT_OTA_CONNECION_UPDATE: "PXI OTA Connecion Update Fail ",
  PXI_OTA_FAILURE_TEXT_OTA_FLASH_ERASE: "PXI OTA Flash Erase Fail ",
  PXI_OTA_FAILURE_TEXT_OTA_SET_FW_INFO: "PXI OTA Set Fw Info Fail ",
  PXI_OTA_FAILURE_TEXT_OTA_FW_UPGRADE: "PXI OTA Set Fw Upgrade Fail ",
  PXI_OTA_FAILURE_TEXT_OTA_FW_WRITE: "PXI OTA Fw Write Fail ",
  PXI_OTA_FAILURE_TEXT_OTA_GET_MTU: "PXI OTA Fw Get MTU Fail ",

  PXI_OTA_FAILURE_TEXT_WRITE_ERROR: "PXI OTA Write Fail ",
  CLIENT_CHARACTERISTIC_CONFIGURATION: "00002902-0000-1000-8000-00805f9b34fb",

  OTA_New_Flow: false,
  mtu_size: 0,
  max_object_size: 0,
  offset: 0,
  crc: 0,
  crc_current: 0,
  crc_last_object: 0,
  PRN: 160,
  notify_obj_create: false,
  notify_prn: false,
  notify_upgrade: false,
  ota_retransmit: false,
  descriptor_write_done: false,
}

















